[package]
name = "libafl_explore"
version = "0.1.0"
edition = "2021"

[dependencies]
libafl = "0.13.0"
libafl_bolts = "0.13.0"
anyhow = "1.0.86"
log = "0.4.21"
simple_logger = "5.0.0"
rayon = "1.10.0"
